steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from=asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service:latest"
      - "-t"
      - "asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service:${SHORT_SHA}"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"

  # Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service:${SHORT_SHA}"

  # Deploy to Cloud Run (Optimized)
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "chatbot-service"
      - "--image=asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service:${SHORT_SHA}"
      - "--platform=managed"
      - "--region=asia-southeast2"
      - "--allow-unauthenticated"
      - "--memory=1Gi" 
      - "--cpu=1" 
      - "--concurrency=80" 
      - "--max-instances=2"
      - "--min-instances=0"
      - "--timeout=300"
      - "--update-env-vars=PROJECT_ID=${PROJECT_ID},GCP_LOGGING_LEVEL=ERROR"
      - "--service-account=333251236087-compute@developer.gserviceaccount.com"
      - "--quiet"

options:
  logging: CLOUD_LOGGING_ONLY
