steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service", "."]
    env:
      - "DOCKER_BUILDKIT=1"

  # Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "chatbot-service", "--image", "asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service", "--platform", "managed", "--region", "asia-southeast2", "--allow-unauthenticated"]

options:
  logging: CLOUD_LOGGING_ONLY
