steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service", "."]
    env:
      - "DOCKER_BUILDKIT=1"

  # Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "chatbot-service"
      - "--image=asia-southeast2-docker.pkg.dev/${PROJECT_ID}/website-porto/chatbot-service"
      - "--platform=managed"
      - "--region=asia-southeast2"
      - "--allow-unauthenticated"
      - "--memory=2Gi"
      - "--cpu=2"
      - "--concurrency=10"
      - "--max-instances=5"
      - "--min-instances=1"
      - "--timeout=300"
      - "--update-env-vars=PROJECT_ID=${PROJECT_ID}"
      - "--service-account=${PROJECT_ID}@appspot.gserviceaccount.com"
      - "--quiet"

options:
  logging: CLOUD_LOGGING_ONLY
